# Generated by Django 5.0.3 on 2024-03-13 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_account_deposit_remove_account_withdraw_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="account_number",
            new_name="account_id",
        ),
    ]
