# Generated by Django 5.0.3 on 2024-03-13 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_rename_account_number_account_account_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deposit",
            old_name="created_at",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="withdraw",
            old_name="created_at",
            new_name="date",
        ),
    ]
