# Generated by Django 5.0.3 on 2024-03-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_rename_created_at_deposit_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.IntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="amount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
